### PR TITLE
Move clipboard plugin declaration out of component

### PR DESCRIPTION
**Pull request by andolojm**
Huh, nevermind, it works, just had to declare it before instantiating vue and not the other way around

### CODE REVIEW

**Review by laroccrj — APPROVED** [review]

**Comment by laroccrj** [comment]
I'm not sure this is better. Cause now the copy to clipboard plugin is being loaded on every page, regardless weather a component on that page uses it or not.

**Comment by andolojm** [comment]
I'm not sure either but we sure are learning here aren't we

**Comment by laroccrj** [comment]
Lol well you can merge if you want.

**Comment by andolojm** [comment]
Committer sucks and is sentenced to 40 lashes with a wet noodle

**Pull request closed without merging**
